### ISSUE TITLE
Feature idea: incremental File DB

### ISSUE THREAD

**Issue by AlCalzone** [ioBroker/db#10]
In light of [recent discussions](https://forum.iobroker.net/post/513415) I propose adding a new file DB variant which does not write the entire multi-megabyte JSON file each time, but rather the changed objects and states.

I've written such a DB for zwave-js but I am sure that we can profit aswell: https://github.com/AlCalzone/jsonl-db
This module shares some ideas from Redis (appending to the file, writing a compressed version in regular intervals) and is freely configurable to limit the load on the file system (minimum number of changes, maximum time interval, etc...)

Conversion of the existing DBs should be as simple as this:
```js
const db = new DB("/path/to/new/file");
await db.open();
await db.importJson("/path/to/old/file");
await db.close();
```

**Comment by Apollon77** [comment]
Could be done after  3.2 release

**Comment by Apollon77** [comment]
We could implement as special db type and so also allow "pre release" with manual npm installation - or we adjust the official file db package
